######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 18 22:51:18 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += EmbSysVisu.h \
    uart.h
FORMS += EmbSysVisu.ui
SOURCES += EmbSysVisu.cpp main.cpp \
    uart.cpp
