######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 19 23:59:29 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /usr/include/qwt-qt4

LIBS += -l qwt-qt4

# Input
HEADERS += Channel.h connectionuart.h EmbSysVisu.h
FORMS += ConnectionUART.ui EmbSysVisu.ui
SOURCES += Channel.cpp connectionuart.cpp main.cpp \
    EmbSysVisu.cpp
